version: 2
jobs:

  integrate:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Environment
          command: |
            git --version
            env | sort | grep "CIRCLE"
      - run:
          name: Intro
          command: ./play --manuscript .circleci/manuscript.yml --part gitintro
      - run:
          name: Swap to target branch and test integration
          command: ./play --manuscript .circleci/manuscript.yml --part integrate

  unittest:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./app/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install --prefix ./app/
      - save_cache:
          paths:
            - ./app/node_modules
          key: v1-dependencies-{{ checksum "./app/package.json" }}
      #- run: npm test --prefix ./functions/

  end-2-end-test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Swap to target branch and integrate
          command: ./play --manuscript .circleci/manuscript.yml --part integrate
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./app/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install --prefix ./app/
      - save_cache:
          paths:
            - ./app/node_modules
          key: v1-dependencies-{{ checksum "./app/package.json" }}
      #- run: npm test --prefix ./functions/

  deliver:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Intro
          command: ./play --manuscript .circleci/manuscript.yml --part gitintro
      - run:
          name: integrate
          command: ./play --manuscript .circleci/manuscript.yml --part integrate
      - run:
          name: Deliver
          command: ./play --manuscript .circleci/manuscript.yml --part deliver

  stage:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./app/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install --prefix ./app/
      - save_cache:
          paths:
            - ./app/node_modules
          key: v1-dependencies-{{ checksum "./app/package.json" }}
      - run:
          name: Install Firebase Tools
          command: sudo npm install --prefix=./firebase-deploy firebase
      - run:
          name: Install Firebase Tools
          command: sudo npm run build-staging --prefix ./app/
      - run:
          name: Deploy to stage
          command: sudo ./firebase-deploy/node_modules/.bin/firebase deploy --only hosting -P staging --token=$FIREBASE_TOKEN
  prod:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./app/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install --prefix ./app/
      - save_cache:
          paths:
            - ./app/node_modules
          key: v1-dependencies-{{ checksum "./app/package.json" }}
      - run:
          name: Install Firebase Tools
          command: sudo npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: deploy firebase
          command: sudo ./firebase-deploy/node_modules/.bin/firebase deploy --only hosting -P production --token=$FIREBASE_TOKEN

workflows:
  version: 2
  dillydally:
    jobs:
      - integrate:
          filters:
            branches:
              only:
                - /ready\/.+/ 
      - unittest: 
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - end-2-end-test: 
          requires:
            - unittest
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/  
      - deliver:
          requires:
            - unittest
            - end-2-end-test
          filters:
            branches:
              only:
                - /ready\/.+/ 
      - stage: # Staging
          requires:
            - unittest
            - end-2-end-test 
          filters:
              branches:
                only:
                  - master
      - prod: # Deploy to prod only by version
          requires:
            - unittest
            - end-2-end-test 
          filters:
              branches:
                ignore: /.*/
              tags:
                only: /^\d+\.\d+\.\d+$/ # Semantic version number (semver.org), followed by optional .(dot)+string https://regex101.com/r/0h0zLr/1
